policies:
  - name: Local Updatecli policies
    config:
      - updatecli/updatecli.d
    values:
      - updatecli/values.d/scm.yaml

  - name: Update githubactions
    policy: ghcr.io/updatecli/policies/autodiscovery/githubaction:0.2.1@sha256:cfddec11464cc09615135f0f1e069f00ad24d28edc7cc6a4e8224e04c3699008
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/githubaction.yaml
