name: updatecli
on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    # Run every hour
    - cron: "0 * * * *"
jobs:
  updatecli:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout"
        uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8" # v5.0.0
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@c87b6e040a27f8a44e60a17a01c08ae9247589d5" # v2
      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: generate_token
        if: github.ref == 'refs/heads/main'
        with:
          app-id: ${{ secrets.UPDATECLIBOT_APP_ID }}
          private-key: ${{ secrets.UPDATECLIBOT_APP_PRIVKEY }}
      - name: "Run updatecli"
        if: github.ref == 'refs/heads/main'
        run: "updatecli compose apply"
        env:
          UPDATECLI_GITHUB_USERNAME: ${{ secrets.UPDATECLI_BOT_GITHUB_ACTOR }}
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
